import os
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
build_options = {'packages': [], 
                 'excludes': [
                    'aiofiles',
                    'aiohttp',
                    'aiolimiter',
                    'aiorun',
                    'aiosignal',
                    'altgraph',
                    'async-timeout',
                    'attrs',
                    'beautifulsoup4',
                    'bottle',
                    'certifi',
                    'cffi',
                    'chardet',
                    'charset-normalizer',
                    'clr-loader',
                    'colorama',
                    'colorspacious',
                    'contourpy',
                    'CTkListbox',
                    # 'customtkinter',
                    'cx-Freeze',
                    'cx-Logging',
                    'cycler',
                    # 'darkdetect',
                    'fonttools',
                    'frozenlist',
                    'idna',
                    'Jinja2',
                    'jsmin',
                    'kiwisolver',
                    'lief',
                    'markdown-it-py',
                    'MarkupSafe',
                    'matplotlib',
                    'mdurl',
                    'multidict',
                    'myjdapi',
                    'numpy',
                    'packaging',
                    'pandas',
                    'pefile',
                    'Pillow',
                    'pip',
                    'ply',
                    'proxy-tools',
                    'pycparser',
                    'pycryptodome',
                    'pygiftparserrgmf',
                    'Pygments',
                    'pyinstaller',
                    'pyinstaller-hooks-contrib',
                    'pyparsing',
                    'python-dateutil',
                    'pythonnet',
                    'pytz',
                    'pywebview',
                    'pywin32-ctypes',
                    'PyYAML',
                    'requests',
                    'rich',
                    'setuptools',
                    'six',
                    'soupsieve',
                    'tabulate',
                    'tkinterweb',
                    'tqdm',
                    'ttkwidgets',
                    'typing_extensions',
                    'urllib3',
                    'yarl',
                 ], 
                 'include_files': [
                     'files/',
                     'template/',
                     'manuals/',
                 ] }

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('OCPWiz.py', base=base, target_name = 'ocpwiz')
]

setup(name='OCPWizard',
      version = '1.0',
      description = 'Offline Course Package Wizard',
      options = {'build_exe': build_options},
      executables = executables)